server:
  port: 8187

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order-db
    username: postgres
    password: admin
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect